/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestImageRouteImport } from './routes/test-image'
import { Route as AfiliadolpslsRouteImport } from './routes/afiliadolpsls'
import { Route as IndexRouteImport } from './routes/index'

const TestImageRoute = TestImageRouteImport.update({
  id: '/test-image',
  path: '/test-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadolpslsRoute = AfiliadolpslsRouteImport.update({
  id: '/afiliadolpsls',
  path: '/afiliadolpsls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliadolpsls': typeof AfiliadolpslsRoute
  '/test-image': typeof TestImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliadolpsls': typeof AfiliadolpslsRoute
  '/test-image': typeof TestImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afiliadolpsls': typeof AfiliadolpslsRoute
  '/test-image': typeof TestImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/afiliadolpsls' | '/test-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/afiliadolpsls' | '/test-image'
  id: '__root__' | '/' | '/afiliadolpsls' | '/test-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfiliadolpslsRoute: typeof AfiliadolpslsRoute
  TestImageRoute: typeof TestImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-image': {
      id: '/test-image'
      path: '/test-image'
      fullPath: '/test-image'
      preLoaderRoute: typeof TestImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliadolpsls': {
      id: '/afiliadolpsls'
      path: '/afiliadolpsls'
      fullPath: '/afiliadolpsls'
      preLoaderRoute: typeof AfiliadolpslsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfiliadolpslsRoute: AfiliadolpslsRoute,
  TestImageRoute: TestImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
